# Dockerfile.training

FROM python:3.10-slim

COPY requirements.txt /requirements.txt

# Установка зависимостей
RUN pip install --no-cache-dir -r /requirements.txt

# Скопируем файлы модели
COPY . /module

# Зададим директорию для работы
WORKDIR /module

# Запустим обучение и отправку метрик
CMD ["python", "main.py"]
